return {
    "lukas-reineke/indent-blankline.nvim",
    -- Pin it because it only works with the newest version of Neovim which I sometimes don't use.
    version = "3.6.2",
    event = "BufReadPre",
    main = "ibl",
    opts = {
        enabled = true,
        indent = {
            char = { "|", "¦", "┆", "┊" },
        },
        -- exclude = {
        -- 	"startify",
        -- 	"dashboard",
        -- 	"dotooagenda",
        -- 	"log",
        -- 	"fugitive",
        -- 	"gitcommit",
        -- 	"packer",
        -- 	"vimwiki",
        -- 	"markdown",
        -- 	"txt",
        -- 	"vista",
        -- 	"help",
        -- 	"todoist",
        -- 	"NvimTree",
        -- 	"peekaboo",
        -- 	"git",
        -- 	"TelescopePrompt",
        -- 	"undotree",
        -- 	"flutterToolsOutline",
        -- 	"hcl",
        -- 	"", -- for all buffers without a file type
        -- },
        -- buftype_exclude = { "terminal", "nofile" },
        -- show_trailing_blankline_indent = false,
        -- show_first_indent_level = true,
        -- show_current_context = true,
        -- space_char = " ",
        -- context_patterns = {
        -- 	"class",
        -- 	"function",
        -- 	"method",
        -- 	"block",
        -- 	"list_literal",
        -- 	"selector",
        -- 	"^if",
        -- 	"^table",
        -- 	"if_statement",
        -- 	"while",
        -- 	"for",
        -- },
    },
}
